//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pap_rui
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class eventos
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public HttpPostedFileBase imagemFile { get; set; }
        public string imagem { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public Nullable<System.DateTime> datafim { get; set; }
        public string descricao { get; set; }
        public string latlang { get; set; }
    }
}
