//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pap_rui
{
    using System;
    using System.Collections.Generic;
    
    public partial class texto
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string descrição { get; set; }
        public int modificadoPor { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
